### ISSUE TITLE
Version 0.31 doesn't work on JDK13 and prints warnings when using JDK 9-12

### ISSUE THREAD

**Issue by srnagar** [jtulach/codesnippet4javadoc#14]
When using codesnippet tool with jdk 9+, I see the warnings below. I followed the instructions provided [here ](https://github.com/jtulach/codesnippet4javadoc#use-with-jdk9) and the doclet itself worked but would be great to not have these warnings. 

```
 javadoc: warning - The old Doclet and Taglet APIs in the packages
[WARNING] com.sun.javadoc, com.sun.tools.doclets and their implementations
[WARNING] are planned to be removed in a future JDK release. These
[WARNING] components have been superseded by the new APIs in jdk.javadoc.doclet.
[WARNING] Users are strongly recommended to migrate to the new APIs.

```

**Comment by jtulach** [comment]
Right. There are warnings printed on JDK9, 10, 11. Removing them is possible, but so far it hasn't been a priority.

**Comment by JonathanGiles** [comment]
The main reason for this report is when javadoc is set to fail on warning we see the unfortunate side effect that making our javadoc better through this doclet (which we are so pleased exists!) results in us not being able to be as stringent on our javadoc quality. At present we have disabled fail on warning in our jdk 11 builds (but still retain them in the jdk 8 builds), but ideally this wouldn't be necessary.

**Comment by jtulach** [comment]
Now, when JDK 13 is out, the problem becomes urgent. The doclet no longer works on JDK 13 - it needs to be updated to new Javadoc API.

**Comment by JonathanGiles** [comment]
@jtulach For my understanding, do you plan to look into resolving this? Thanks

**Comment by jtulach** [comment]
Yes, I will look into the problem. I assume it will be fixed by end of
October, 2019.

st 2. 10. 2019 v 20:22 odesílatel Jonathan Giles <notifications@github.com>
napsal:

**Comment by JonathanGiles** [comment]
Excellent, thanks for taking this on, it is much appreciated.

**Comment by jtulach** [comment]
I haven't gotten to address the problem yet, but I keep it in my TODO list.

**Comment by JaroslavTulach** [comment]
There is a branch [JDK13](https://github.com/jtulach/codesnippet4javadoc/tree/JDK13) and since 0b19b4fd it seems to pass on all tests on JDK13. The next step is to make sure the code also runs on JDK8 and JDK11.

**Comment by srnagar** [comment]
I was testing JDK13 branch using maven javadoc version `3.1.1` and found that the new configuration options added since `2.10.3` (which is what is used in the `testing` module) don't work. For e.g. `doclint`, `footer`, `group` etc. throw NullPointerException. This is happening only on JDK13 branch and master branch works with javadoc plugin version 3.1.1.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:javadoc (for-testing) on project testing: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - javadoc: error - invalid flag: -Xdoclint:all
[ERROR] Exception in thread "main" java.lang.NullPointerException
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.showUsage(Start.java:309)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.showDocletOption(Start.java:285)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[ERROR]         at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
[ERROR]         at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[ERROR]         at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR]         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.showDocletOptions(Start.java:271)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.usage(Start.java:201)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.usage(Start.java:175)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:441)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
```

Here's the pom configuration I used in `testing` module:

```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-javadoc-plugin</artifactId>
	<version>3.1.1</version>
	<dependencies>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
		</dependency>
	</dependencies>
	<executions>
		<execution>
			<id>for-testing</id>
			<phase>generate-test-resources</phase>
			<goals>
				<goal>javadoc</goal>
			</goals>
			<configuration>
				<outputDirectory>${project.build.directory}/test-classes/</outputDirectory>
				<reportOutputDirectory>${project.build.directory}/test-classes/</reportOutputDirectory>
			</configuration>
		</execution>
	</executions>
	<configuration>
		<groups>
			<group>
				<title>abc</title>
				<packages>org.apidesign.javadoc.testing*</packages>
			</group>
		</groups>
		<doclint>all</doclint>
		<doclet>org.apidesign.javadoc.codesnippet.Doclet</doclet>
		<docletArtifact>
			<groupId>${project.groupId}</groupId>
			<artifactId>codesnippet-doclet</artifactId>
			<version>${project.version}</version>
		</docletArtifact>
		<additionalJOption>${debug}</additionalJOption>
		<additionalOptions>
			<additionalOption>-maxLineLength 80</additionalOption>
			<additionalOption>-snippetpath src/test/java</additionalOption>
			<additionalOption>-snippetclasses ".*Snippet.*"</additionalOption>
			<additionalOption>-hiddingannotation java.lang.Deprecated</additionalOption>
			<additionalOption>-hiddingannotation org.apidesign.javadoc.testing.HiddenSnippets.Invisible</additionalOption>
		</additionalOptions>
		<additionalJOptions>
			<opt>-J${add.opens}</opt>
		</additionalJOptions>
	</configuration>
</plugin>
```

I ran `mvn clean install` and got the above error.

**Comment by JaroslavTulach** [comment]
New version is ready for testing: 1c9e934 -  `doclint`, `footer`, `group` & co. arguments are now supported. The good news is that we no longer need to use `--add-opens`. Let's do some more testing and then release new version `0.50`.

**Comment by srnagar** [comment]
That's great news! Thank you for fixing this!

**Comment by JonathanGiles** [comment]
Would love to see a new release out that includes this fix. It will let us fail our build when code snippets are not found, etc, rather than logging them but not failing the build. Do you have any idea when you might make this release? Thanks!

**Comment by srnagar** [comment]
@jtulach I tested the latest code in JDK13 branch and when I tried to run `mvn install`, I see the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:javadoc (for-testing) on project testing: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - java.lang.IllegalArgumentException: wrong number of arguments
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at com.sun.tools.oldlets.javadoc.main.SymbolKind.invokeOrNull(SymbolKind.java:330)
[ERROR]         at com.sun.tools.oldlets.javadoc.main.Start.parseAndExecute(Start.java:369)
[ERROR]         at com.sun.tools.oldlets.javadoc.main.Start.begin(Start.java:232)
[ERROR]         at com.sun.tools.oldlets.javadoc.main.Start.begin(Start.java:225)
[ERROR]         at org.apidesign.javadoc.codesnippet.Doclet.run(Doclet.java:384)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
[ERROR] CodesnippetDoclet: error - fatal exception
[ERROR] javadoc: error - an unknown error has occurred
[ERROR]
[ERROR] Command line was: "C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin\javadoc.exe" @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'C:\Users\srnagar\home\azure\github\doclet\codesnippet4javadoc\testing\target\test-classes\apidocs' dir.

```

I removed the `testing` module and `mvn install` succeeded. When I used this jar in our library, I see the same error.

**Comment by JaroslavTulach** [comment]
I guess @srnagar reply answers @JonathanGiles question - it's not yet working properly. The [latest commit](4e52c0e1b9b248cd47cad389d5b4dcf997477416) fails on JDK8 due to problems with [#16|doclinting]. Plus there is the error reported by @srnagar.

It makes little sense to produce a release when it is known the code isn't yet working (even for @srnagar's usecase), I'd say.

**Comment by JonathanGiles** [comment]
For what it is worth, @srnagar and I have the same use case as we are on the same team :-)

**Comment by JaroslavTulach** [comment]
I've just solved the #16 problem. The commit 809538055d81994f2e0856596a0d34291b0c2136 has just passed all the gates. I think I am ready to release version `0.50`.

I wasn't able to reproduce the [above problem](https://github.com/jtulach/codesnippet4javadoc/issues/14#issuecomment-563459186) - neither with JDK11.0.2, neither with JDK11.0.5 - but I am on Linux, not Windows.

**Comment by jtulach** [comment]
Version `0.50` has just been uploaded to Maven central.

**Comment by JaroslavTulach** [comment]
> [ERROR] Exit code: 1 - java.lang.IllegalArgumentException: wrong number of arguments
> [ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Hopefully addressed once https://github.com/jtulach/codesnippet4javadoc/commits/jtulach/NoSuchMethodError gets integrated - e.g. in version 0.51

**Comment by srnagar** [comment]
@JaroslavTulach I switched to the latest released version `0.51` and observed the following two errors:

1. `-suppressMissingLinkWarnings` flag is no longer supported which was added in version `0.32`.
```
[ERROR] MavenReportException: Error while generating Javadoc:
Exit code: 1 - javadoc: error - invalid flag: -suppressMissingLinkWarnings
```
2. After removing the above flag from maven configuration, I see the following error:

```
javadoc: error - an unknown error has occurred

Command line was: "C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin\javadoc.exe" @options @argfile

Refer to the generated Javadoc files in 'path/to/target/apidocs' dir.

org.apache.maven.reporting.MavenReportException:
Exit code: 1 - path/to/HttpResponse.java:7: error: package reactor.core.publisher does not exist
import reactor.core.publisher.Flux;
                             ^
path/to/HttpResponse.java:8: error: package reactor.core.publisher does not exist
import reactor.core.publisher.Mono;
                             ^
path/to/HttpRequest.java:7: error: package reactor.core.publisher does not exist
import reactor.core.publisher.Flux;
                             ^
path/to/HttpResponse.java:74: error: cannot find symbol
    public abstract Flux<ByteBuffer> getBody();
```

**Comment by jtulach** [comment]
Alas, the new versions `0.5x` had to undergo a significant rewrite due to removal of old Javadoc API from JDK 13. I am sorry to omit the functionality introduced by #18 - this is what happens when there are no tests to cover the behavior. Feel free to port it to `0.5x` versions with another PR.

I am not sure what is the cause of `error - an unknown error has occurred`. I have never seen such error myself. I'll investigate if you give me a reproducer.

**Comment by srnagar** [comment]
@JaroslavTulach I have a sample repo to reproduce the above error - https://github.com/srnagar/snippet-demo

### Setup:
[AdoptOpenJDK 11 with hotspot](https://adoptopenjdk.net/?=openjdk11&jvmVariant=hotspot)
Maven - 3.6
CodeSnippet version 0.51

### Steps to reproduce:
1. Clone the repository - https://github.com/srnagar/snippet-demo
2. Run `mvn javadoc:javadoc -f pom.xml`
3. Note the errors from running the above command (similar to the one in my previous comment)
4. Generated javadoc
```
public static <any> getFlux()
Returns a Flux of integers.
Returns:
A flux of integers.
```

### About the repo:
It's a very simple Maven project with a single Java class `Main.java` which has Javadoc that links to an external dependency class - `Flux` from [reactor-core](https://github.com/reactor/reactor-core)

### Previous version
Change the codesnippet version to 0.32 on [line 58](https://github.com/srnagar/snippet-demo/blob/master/pom.xml#L58) and re-run `mvn javadoc:javadoc -f pom.xml`. The javadoc is generated successfully without any errors and `Flux` is hyperlinked to refer to it's javadoc.

```
public static Flux<Integer> getFlux()
Returns a Flux of integers.
Returns:
A flux of integers.
```

PS: I am working on re-introducing `suppressMissingLinkWarning` flag that was introduced in #18 and will send another PR soon.

**Comment by jtulach** [comment]
Thanks. I've reproduced the error.

**Comment by jtulach** [comment]
The Flux problem is Solved by 43b7cd9.

**Comment by srnagar** [comment]
Great, thanks for the quick turnaround! I will run a quick test with the latest code and validate both changes (#19 and [43b7cd9](https://github.com/jtulach/codesnippet4javadoc/commit/43b7cd98446d81253161ddcf061833998e092b37)).

**Comment by jtulach** [comment]
The `0.52` bits are now [staged and ready for testing](https://maven.java.net/content/repositories/orgapidesign-1088/).

**Comment by srnagar** [comment]
@jtulach I just tested 0.52 and everything looks good. Thanks again for fixing this! Please let me know when this is released to maven central.
